### ISSUE TITLE
Segfault upon launch on Arch Linux

### ISSUE THREAD

**Issue by hosaka** [mstg/zx#1]
Hey,

I'm getting a segfault when trying to launch zx.
`[1]    18365 segmentation fault (core dumped)  zx`
Compiled from AUR on 
`4.5.1-1-ARCH`

Anyway to enable debug info? There's a .zx.log file which is empty and I have no .zxconfig in place either.

**Comment by mstg** [comment]
I'll take a look. Maybe something broke with an update.

**Comment by hosaka** [comment]
Would be happy to help with anything!

**Comment by hosaka** [comment]
in dmesg i see the following:
`zx[12603]: segfault at 7f7b00000000 ip 00007f7be2e8b646 sp 00007f7bdc4dba28 error 4 in libc-2.23.so[7f7be2e0d000+198000]`

**Comment by mstg** [comment]
try writing a config, maybe some problems with the init with default values.
i'll try to find out whats wrong

**Comment by hosaka** [comment]
Hey, I have tried adding the config. But the segfault persists. It happens randomly, i'll get it to launch at times, sometimes it would crash straight away, other times it'll crash only when adding a window to scratchpad.
Aside from generic glib message:
`GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed`

I also ran valgrind with zx and observed the following:

```
(process:2531): GLib-CRITICAL **: g_convert: assertion 'str != NULL' failed
==2531== Invalid read of size 1
==2531==    at 0x4C2DBA2: strlen (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2531==    by 0x4037D1: add_win (zx.c:253)
==2531==    by 0x40385D: add_win_list (zx.c:318)
==2531==    by 0x4E7C28C: g_list_foreach (in /usr/lib/libglib-2.0.so.0.4800.0)
==2531==    by 0x4E7C28C: g_list_foreach (in /usr/lib/libglib-2.0.so.0.4800.0)
==2531==    by 0x403B26: draw_wins_main (zx.c:364)
==2531==    by 0x403E19: bg_thread (zx.c:424)
==2531==    by 0x5F5A423: start_thread (in /usr/lib/libpthread-2.23.so)
==2531==    by 0x6257CBC: clone (in /usr/lib/libc-2.23.so)
==2531==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==2531== 
==2531== 
==2531== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==2531==  Access not within mapped region at address 0x0
==2531==    at 0x4C2DBA2: strlen (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2531==    by 0x4037D1: add_win (zx.c:253)
==2531==    by 0x40385D: add_win_list (zx.c:318)
==2531==    by 0x4E7C28C: g_list_foreach (in /usr/lib/libglib-2.0.so.0.4800.0)
==2531==    by 0x4E7C28C: g_list_foreach (in /usr/lib/libglib-2.0.so.0.4800.0)
==2531==    by 0x403B26: draw_wins_main (zx.c:364)
==2531==    by 0x403E19: bg_thread (zx.c:424)
==2531==    by 0x5F5A423: start_thread (in /usr/lib/libpthread-2.23.so)
==2531==    by 0x6257CBC: clone (in /usr/lib/libc-2.23.so)
```

This suggest zx.c:253 is the culprit. But I didn't notice anything out of place after a quick glance. I didn't look very hard though :)

**Comment by mstg** [comment]
Sorry for digging up an old issue, but I still can't reproduce this. I am also running zx on Arch Linux but have not encountered this yet.
